/*
 * File: main.c
 * Author: Stephen Richardson 
 * Date: 11/7/20 9:00 PM
 * Description: Create a Gradebook from a CSV file using the Student struct
 *       and a dynamically allocated array
 */
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <errno.h>
#include "Student.h"

/* growArray: Allocate additional space in the heap for a larger array
 *    copy the data over and free the old array to stopp data leaks
 *    returns NULL on error, leaving original array unchanged
 * array - a pointer to the array of pointers of Student structs
 * currSize - an int specifying the arrays current size
 * newSize - the size to make the array
 */
Student ** growArray(Student ** array, int currSize, int newSize) {
   // validate parameters
   if (array == NULL || newSize < currSize) {
      return NULL;
   }

   //create new array, and check for successful creation
   Student ** newArray = (Student **)malloc(sizeof(Student*) * newSize);
   if (newArray == NULL) {
      return NULL;
   }

   //copy data to new array and clear out old one.
   for (int i = 0; i < currSize; i++) {
      newArray[i] = array[i];
      //DestroyStudent(array[i]);
      fprintf(stderr, "%d\n", i);
   }
   free(array);
   
   //display results
   fprintf(stdout, "Growing array: %d -> %d\n", currSize, newSize);

   return newArray;
}

/*
 * qSortCmp: Passes void pointers generated by qsort to CompareStudents function
 *       and returns the result for qsort to use.
 * studentA - void ptr to the first student
 * studentB - void ptr to the second student
 */
int qSortCmp (const void * studentA, const void * studentB) {
   return CompareStudents(studentA, studentB);
}

int main(int argc, char * argv[]) {
   FILE * datafile;
   char * fileName;
   Student ** gradebook;
   int arraySize = 8;
   const int MAX_STRING_SIZE = 151;

   /* variables for reading from .csv */
   char studentFirstName[MAX_STRING_SIZE];
   char studentLastName[MAX_STRING_SIZE];
   int studentID = -1;
   int studentGrade = -1;

   int numStudents = 0;
   int paramsRead = 0;

   // if too few or too many arguments, exit program
   if (argc != 2) {
      fprintf(stderr, "Usage: ./myprog <gradebook.csv>\n");
      exit (1);
   }

   // if file won't open, or doesn't exist, exit program
   errno = 0;
   fileName = argv[1];
   datafile = fopen(fileName, "r");
   if (datafile == NULL) {
      perror("fopen");
      exit(1);
   }

   //create array with the initial 8 slots
   gradebook = (Student **)malloc(sizeof(Student * ) * arraySize);
   fprintf(stdout, "Array initialized to %d students\n", arraySize);

   //fill up array with students from file
   fprintf(stdout, "Populating gradebook from %s.....\n", fileName);
   
   numStudents = 0;
   while (!feof(datafile)) {
      // double the array if it is full
      if (numStudents == arraySize) {
         Student ** tempptr = growArray(gradebook, arraySize, arraySize * 2);
         
         //if allocation failed, clear memory and exit program
         if (tempptr == NULL) {
            fprintf(stderr, "Error: failed to increase array size\n");
            fprintf(stderr, "Clearing memory and exiting program\n");
            for (int i = 0; i < arraySize; i++) {
               DestroyStudent(gradebook[i]);
            }
            free(gradebook);
         }

         //otherwise, it worked, so update gradebook and arraySize
         gradebook = tempptr;
         arraySize *= 2;
      }
      
      paramsRead = fscanf(datafile, "%150[^,],%150[^,],%d,%d\n", studentLastName,
                  studentFirstName, &studentID, &studentGrade);
      if (paramsRead == 4) {
         gradebook[numStudents] = CreateStudent(studentLastName, studentFirstName,
                  studentID, studentGrade);
         //if failed to allocate, clear memory and exit program
         if (gradebook[numStudents] == NULL) {
            fprintf(stderr, "Error: Failed to allocate student. Clearing memory and exiting program");
            for (int i = 0; i < arraySize; i++) {DestroyStudent(gradebook[i]);}
            free(gradebook);
            exit(1);
         }

         numStudents++;
         
      } else {
         fprintf(stderr, "Error: failed to correctly read from csv\n");
      }
   }

   //close datafile
   fclose(datafile);

   //display results
   fprintf(stdout, "Successfully loaded %d students\n", numStudents);

   // sort students using qsort
   qsort(gradebook, numStudents,sizeof(Student *), qSortCmp);

   //print sorted students
   for (int i = 0; i < numStudents; i++) {
      PrintStudent(gradebook[i]);
   }

   // Clear up the memeory
   for (int i = 0; i < numStudents; i++) {
      DestroyStudent(gradebook[i]);
   }
   free(gradebook);

   return 0;
}